### ISSUE TITLE
Updating description.

### ISSUE THREAD

**Issue by Fozik1** [AdExBlockchain/adex-dapp#10]
v.2.0.3-beta
Saving updated description gives an error:
https://i.imgur.com/cF2dr4p.png

Err updating item: - <!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>Cannot PUT /items</pre> </body> </html>

in chrome 65.0.3325.146

**Comment by IvoPaunov** [comment]
Fixed, it was node issue.
