### ISSUE TITLE
Cancel button does not work

### ISSUE THREAD

**Issue by Rapso** [AdExBlockchain/adex-dapp#2]
Checked in, "New Slot", "Create Account" and "Restore Account" Dialogs, Cancel button does not close the dialog.

**Comment by Ivshti** [comment]
We're aware of that, thanks for submitting, will be fixed soon

**Comment by IvoPaunov** [comment]
[Fixed](https://github.com/AdExBlockchain/adex-dapp/compare/v2.0.7...v2.0.8)
