### ISSUE TITLE
Reset button for clearing out form should be added.

### ISSUE THREAD

**Issue by avipatel91** [AdExBlockchain/adex-dapp#5]
A form with values that was toggled off on purpose will still have those old values when user wants to enter new/different values. Currently, the form does not clear on toggle since it can be toggled/canceled/x'd by accident ([mentioned here](https://github.com/AdExBlockchain/adex-dapp/issues/4#issuecomment-348764728)). However, there can be instances where it was toggled off on purpose. For those cases, a reset button to clear the form might be handy to clear out old inputs that haven't been saved.

**Comment by IvoPaunov** [comment]
I'll discuss that with our UI/UX expert but ([IMO](https://github.com/AdExBlockchain/adex-dapp/issues/4#issuecomment-348764728)) the solution is 'reset button' and reset on 'cancel'.

P.S. In the next few days I'll work on 'we3 branch' and there might be same structure changes for the reducers and stepper forms and this is the reason I'll leave ([Adding action for cancel in form. #3](https://github.com/AdExBlockchain/adex-dapp/pull/3)) open for now.

**Comment by avipatel91** [comment]
Sounds good. Meanwhile, I will play around with UI and see if there are any bugs. If you know of any that you want me to take up, let me know.

**Comment by IvoPaunov** [comment]
[Fixed](https://github.com/AdExBlockchain/adex-dapp/compare/v2.0.7...v2.0.8)
