### ISSUE TITLE
When I press on adex logo it's opening a alert popup saying : "test"

### ISSUE THREAD

**Issue by silviucpp** [AdExBlockchain/adex-dapp#7]
Just press on the adex logo:

![adex_dapp](https://user-images.githubusercontent.com/4814731/36717073-4f41b640-1ba5-11e8-971a-bea5532e2469.jpg)

**Comment by IvoPaunov** [comment]
[Fixed](https://github.com/AdExBlockchain/adex-dapp/commit/d5c8c9d44577f89ed131f7437bfc0e4d6f8ad4b6)
